### ISSUE TITLE
spint has pysal as a dependency, should be libpysal

### ISSUE THREAD

**Issue by sjsrey** [pysal/spint#2]
Realizing that `spreg` is not yet a stand-alone package, this can't be fixed at present. Just raising it to flag issues we have to fix as part of the larger [pysal refactoring](https://github.com/pysal/pysal/wiki/PEP-13:-Refactor-PySAL-Using-Submodules).

```Traceback (most recent call last):
  File "/home/serge/anaconda3/envs/pysal2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/serge/anaconda3/envs/pysal2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/serge/anaconda3/envs/pysal2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/serge/Documents/p/pysal/src/pysal-reorg/spint/spint/__init__.py", line 1, in <module>
    from . import gravity
  File "/home/serge/Documents/p/pysal/src/pysal-reorg/spint/spint/gravity.py", line 21, in <module>
    from pysal.spreg import user_output as User
ImportError: No module named pysal.spreg
```

**Comment by TaylorOshan** [comment]
Sounds good. If I recall, spreg will eventually be stand-alone as well, so no need to make changes other than pysal.spreg-->spreg onces spreg ready?

**Comment by ljwolf** [comment]
spreg is ready

**Comment by ljwolf** [comment]
:smile: :tada:

**Comment by pedrovma** [comment]
This is very nice indeed!

**Comment by jGaboardi** [comment]
Is this issue resolved then?

**Comment by ljwolf** [comment]
I think so
